-- Generated by scripts/generate-seed-sql.mjs
insert into public.bottles (id, name, distillery, proof, category, image_url, flavor_tags)
values
  ('b001', 'Blanton''s Single Barrel', 'Buffalo Trace', 93, 'Bourbon', null, array['vanilla', 'caramel']::text[]),
  ('b002', 'Eagle Rare 10 Year', 'Buffalo Trace', 90, 'Bourbon', null, array['oak', 'toffee']::text[]),
  ('b003', 'Weller Special Reserve', 'Buffalo Trace', 90, 'Wheated Bourbon', null, array['honey', 'vanilla']::text[]),
  ('b004', 'Buffalo Trace', 'Buffalo Trace', 90, 'Bourbon', null, array['brown sugar', 'spice']::text[]),
  ('b005', 'Elijah Craig Small Batch', 'Heaven Hill', 94, 'Bourbon', null, array['cinnamon', 'oak']::text[]),
  ('b006', 'Woodford Reserve Distiller''s Select', 'Brown-Forman', 90.4, 'Bourbon', null, array['cocoa', 'caramel']::text[]),
  ('b007', 'Four Roses Single Barrel', 'Four Roses', 100, 'Bourbon', null, array['pear', 'spice']::text[]),
  ('b008', 'Maker''s Mark', 'Beam Suntory', 90, 'Wheated Bourbon', null, array['wheat', 'caramel']::text[]),
  ('b009', 'Maker''s Mark Cask Strength', 'Beam Suntory', 109, 'Wheated Bourbon', null, array['toffee', 'baking spice']::text[]),
  ('b010', 'Russell''s Reserve 10 Year', 'Wild Turkey', 90, 'Bourbon', null, array['orange peel', 'oak']::text[]),
  ('b011', 'Wild Turkey Rare Breed', 'Wild Turkey', 116.8, 'Bourbon', null, array['tobacco', 'honey']::text[]),
  ('b012', 'Knob Creek 9 Year', 'Jim Beam', 100, 'Bourbon', null, array['peanut brittle', 'char']::text[]),
  ('b013', 'Basil Hayden', 'Jim Beam', 80, 'High Rye Bourbon', null, array['pepper', 'light oak']::text[]),
  ('b014', 'Booker''s', 'Jim Beam', 125, 'Bourbon', null, array['roasted nuts', 'smoke']::text[]),
  ('b015', 'Baker''s 7 Year', 'Jim Beam', 107, 'Bourbon', null, array['chocolate', 'nuts']::text[]),
  ('b016', 'Old Forester 86 Proof', 'Brown-Forman', 86, 'Bourbon', null, array['banana', 'oak']::text[]),
  ('b017', 'Old Forester 1920', 'Brown-Forman', 115, 'Bourbon', null, array['dark cherry', 'molasses']::text[]),
  ('b018', 'Old Forester 1910', 'Brown-Forman', 93, 'Bourbon', null, array['marshmallow', 'char']::text[]),
  ('b019', '1792 Small Batch', 'Barton 1792', 93.7, 'Bourbon', null, array['rye spice', 'caramel']::text[]),
  ('b020', '1792 Full Proof', 'Barton 1792', 125, 'Bourbon', null, array['brown sugar', 'pepper']::text[]),
  ('b021', 'Larceny Small Batch', 'Heaven Hill', 92, 'Wheated Bourbon', null, array['bread', 'honey']::text[]),
  ('b022', 'Larceny Barrel Proof', 'Heaven Hill', 122, 'Wheated Bourbon', null, array['caramel', 'oak']::text[]),
  ('b023', 'Henry McKenna 10 Year', 'Heaven Hill', 100, 'Bottled in Bond Bourbon', null, array['clove', 'vanilla']::text[]),
  ('b024', 'Evan Williams Bottled in Bond', 'Heaven Hill', 100, 'Bourbon', null, array['toffee', 'corn']::text[]),
  ('b025', 'Evan Williams Single Barrel', 'Heaven Hill', 86.6, 'Bourbon', null, array['apple', 'oak']::text[]),
  ('b026', 'Angel''s Envy Bourbon', 'Louisville Distilling', 86.6, 'Finished Bourbon', null, array['port', 'vanilla']::text[]),
  ('b027', 'Michter''s US*1 Bourbon', 'Michter''s', 91.4, 'Bourbon', null, array['stone fruit', 'honey']::text[]),
  ('b028', 'Michter''s US*1 Sour Mash', 'Michter''s', 86, 'American Whiskey', null, array['citrus', 'toffee']::text[]),
  ('b029', 'Jefferson''s Very Small Batch', 'Jefferson''s', 82.3, 'Bourbon', null, array['vanilla', 'orange']::text[]),
  ('b030', 'Belle Meade Reserve', 'Nelson''s Green Brier', 108.3, 'Bourbon', null, array['spice', 'cherry']::text[]),
  ('b031', 'New Riff Single Barrel', 'New Riff', 100, 'Bourbon', null, array['mint', 'caramel']::text[]),
  ('b032', 'Smoke Wagon Small Batch', 'Nevada H&C', 100, 'Bourbon', null, array['toffee', 'graham cracker']::text[]),
  ('b033', 'Penelope Architect', 'Penelope', 104, 'Bourbon', null, array['vanilla', 'french oak']::text[]),
  ('b034', 'Barrell Bourbon Batch 35', 'Barrell Craft Spirits', 115, 'Bourbon', null, array['dark fruit', 'spice']::text[]),
  ('b035', 'Wyoming Small Batch Bourbon', 'Wyoming Whiskey', 88, 'Bourbon', null, array['honey', 'apple']::text[]),
  ('b036', 'High West American Prairie', 'High West', 92, 'Bourbon', null, array['caramel', 'orange']::text[]),
  ('b037', 'Bulleit Bourbon', 'Bulleit', 90, 'High Rye Bourbon', null, array['rye spice', 'clove']::text[]),
  ('b038', 'Bulleit 10 Year', 'Bulleit', 91.2, 'High Rye Bourbon', null, array['dried fruit', 'oak']::text[]),
  ('b039', 'Jack Daniel''s Bonded', 'Jack Daniel Distillery', 100, 'Tennessee Whiskey', null, array['banana', 'char']::text[]),
  ('b040', 'Jack Daniel''s Single Barrel Barrel Proof', 'Jack Daniel Distillery', 130, 'Tennessee Whiskey', null, array['maple', 'oak']::text[]),
  ('b041', 'Peerless Small Batch Bourbon', 'Kentucky Peerless', 108, 'Bourbon', null, array['honey', 'cocoa']::text[]),
  ('b042', 'Stagg', 'Buffalo Trace', 127, 'Bourbon', null, array['dark cherry', 'clove']::text[]),
  ('b043', 'Colonel E.H. Taylor Small Batch', 'Buffalo Trace', 100, 'Bottled in Bond Bourbon', null, array['toffee', 'pepper']::text[]),
  ('b044', 'Weller Antique 107', 'Buffalo Trace', 107, 'Wheated Bourbon', null, array['cinnamon', 'cherry']::text[]),
  ('b045', 'Weller 12 Year', 'Buffalo Trace', 90, 'Wheated Bourbon', null, array['oak', 'honey']::text[]),
  ('b046', 'Old Ezra 7', 'Lux Row', 117, 'Bourbon', null, array['caramel', 'spice']::text[]),
  ('b047', 'Rebel Cask Strength', 'Lux Row', 113, 'Wheated Bourbon', null, array['vanilla', 'oak']::text[]),
  ('b048', 'Jim Beam Black', 'Jim Beam', 86, 'Bourbon', null, array['caramel', 'char']::text[]),
  ('b049', 'Bib & Tucker 6 Year', 'Deutsch Family', 92, 'Bourbon', null, array['cocoa', 'pepper']::text[]),
  ('b050', 'Redwood Empire Lost Monarch', 'Redwood Empire', 90, 'Blended Bourbon', null, array['orange', 'vanilla']::text[])
on conflict (id) do update set
  name = excluded.name,
  distillery = excluded.distillery,
  proof = excluded.proof,
  category = excluded.category,
  image_url = excluded.image_url,
  flavor_tags = excluded.flavor_tags;

insert into public.stores (id, name, lat, lng, city, state, verified)
values
  ('s001', 'Cheers Liquor', 36.1627, -86.7816, 'Nashville', 'TN', false),
  ('s002', 'Bluegrass Spirits', 38.2527, -85.7585, 'Louisville', 'KY', true),
  ('s003', 'Barrel House Wine and Spirits', 35.9606, -83.9207, 'Knoxville', 'TN', true)
on conflict (id) do update set
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  city = excluded.city,
  state = excluded.state,
  verified = excluded.verified;

insert into public.listings (id, bottle_id, store_id, price, in_stock, notes, last_updated)
values
  ('l001', 'b001', 's001', 129.99, true, 'Store pick', now()),
  ('l002', 'b001', 's002', 119.99, true, null, now()),
  ('l003', 'b002', 's001', 59.99, true, null, now()),
  ('l004', 'b002', 's002', 62.99, false, null, now()),
  ('l005', 'b003', 's003', 74.99, true, 'Limited shelf stock', now()),
  ('l006', 'b004', 's003', 94.99, true, null, now())
on conflict (id) do update set
  bottle_id = excluded.bottle_id,
  store_id = excluded.store_id,
  price = excluded.price,
  in_stock = excluded.in_stock,
  notes = excluded.notes,
  last_updated = now();
